//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarnelTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public string SenderName { get; set; }
        public string SenderMail { get; set; }
        public string FeedBackTitle { get; set; }
        public string FeedBackContent { get; set; }
        public bool State { get; set; }
        public System.DateTime Create_on { get; set; }
    }
}
