//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarnelTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgFood
    {
        public int Img_Foods_Id { get; set; }
        public string Img_Foods { get; set; }
        public byte Img_Foods_Sort { get; set; }
        public string Food_Code { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
