//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarnelTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImgHotel
    {
        public int Img_Hotels_Id { get; set; }
        public string Img_Hotels { get; set; }
        public byte Img_Hotels_Sort { get; set; }
        public string Hotel_Id { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
