//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarnelTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.ImgRooms = new HashSet<ImgRoom>();
        }
    
        public string Room_Id { get; set; }
        public string Room_Type { get; set; }
        public string Room_Name { get; set; }
        public Nullable<System.TimeSpan> Room_Start { get; set; }
        public Nullable<System.TimeSpan> Room_Stop { get; set; }
        public Nullable<decimal> Room_Cost { get; set; }
        public string Hotel_Id { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImgRoom> ImgRooms { get; set; }
    }
}
