//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KarnelTravel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public string Vehicle_Id { get; set; }
        public string Vehicle_Name { get; set; }
        public Nullable<decimal> Vehicle_Price { get; set; }
        public Nullable<int> Vehicle_Weight { get; set; }
        public string Vehicle_Img { get; set; }
        public string Transportation_Id { get; set; }
    
        public virtual Transportation Transportation { get; set; }
    }
}
