//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vihicle
    {
        public string Vihicle_Id { get; set; }
        public string Vihicle_Name { get; set; }
        public Nullable<int> Vihicle_Weight { get; set; }
        public string Vihicle_Img { get; set; }
        public string Transportation_Id { get; set; }
    
        public virtual Transportation Transportation { get; set; }
    }
}
