use KarnelTravel
--Custommer
Insert into Customer(Customer_Id,Customer_LastName,Customer_FirstName,Customer_Bithday,Customer_Gender,Customer_Phone,Customer_Address,Customer_Email,Customer_Possport) values ('DTHUY','Tuan','Huy','1/2/1997',1,'(+84)925028450','Tien Thuy, Chau Thanh, Ben Tre','yami@gmail.com','A001849');
Insert into Customer(Customer_Id,Customer_LastName,Customer_FirstName,Customer_Bithday,Customer_Gender,Customer_Phone,Customer_Address,Customer_Email,Customer_Possport) values ('NTYN','Nhi','Yen','8/31/1996',0,'(+84)925028150','Can Tho','yamino@gmail.com','A001867');
Insert into Customer(Customer_Id,Customer_LastName,Customer_FirstName,Customer_Bithday,Customer_Gender,Customer_Phone,Customer_Address,Customer_Email,Customer_Possport) values ('PNHS','Son','Pham','12/31/1998',1,'(+84)925028445','Hong Nghu','yamishiba@gmail.com','A001849');
Insert into Customer(Customer_Id,Customer_LastName,Customer_FirstName,Customer_Bithday,Customer_Gender,Customer_Phone,Customer_Address,Customer_Email,Customer_Possport) values ('TTP','Tran','Phong','11/2/1991',1,'(+84)925128450','Phong Dien','hikari@gmail.com','A001843');
Insert into Customer(Customer_Id,Customer_LastName,Customer_FirstName,Customer_Bithday,Customer_Gender,Customer_Phone,Customer_Address,Customer_Email,Customer_Possport) values ('TTT','Thai','Tan','1/2/1995',1,'(+84)925028441','Ca Mau, Minh Hai','fuu@gmail.com','A101849');
Insert into Customer(Customer_Id,Customer_LastName,Customer_FirstName,Customer_Bithday,Customer_Gender,Customer_Phone,Customer_Address,Customer_Email,Customer_Possport) values ('NDT','Trung','Duc','1/4/1998',1,'(+84)925828450','Kien Giang, An Giang','yamiku@gmail.com','A0301849');
Insert into Customer(Customer_Id,Customer_LastName,Customer_FirstName,Customer_Bithday,Customer_Gender,Customer_Phone,Customer_Address,Customer_Email,Customer_Possport) values ('NAT','Tuan','Anh','1/2/1995',1,'(+84)925029450','Ninh Kieu,Can Tho','yamino@gmail.com','B001849');
Insert into Customer(Customer_Id,Customer_LastName,Customer_FirstName,Customer_Bithday,Customer_Gender,Customer_Phone,Customer_Address,Customer_Email,Customer_Possport) values ('OTML','Linh','My','1/2/1978',1,'(+84)925038450','Go Cong, Tien Giang','otmlinh@cusc.ctu.edu.com','C001849');
Insert into Customer(Customer_Id,Customer_LastName,Customer_FirstName,Customer_Bithday,Customer_Gender,Customer_Phone,Customer_Address,Customer_Email,Customer_Possport) values ('LHH','Huong','Luong','1/2/1988',1,'(+84)925028454','CaiRang, Can Tho','huongluonf@gmail.com','D001849');
Insert into Customer(Customer_Id,Customer_LastName,Customer_FirstName,Customer_Bithday,Customer_Gender,Customer_Phone,Customer_Address,Customer_Email,Customer_Possport) values ('NHH24','Hai','24','1/2/1993',1,'(+84)925088450','Yen Bai','nana@gmail.com','R001849');